//
//  Annonce.swift
//  KeepMyPetApp
//
//  Created by Apprenant 23 on 24/03/2022.
//

import Foundation
struct Annonce: Identifiable {
    var id=UUID()
    var photoDeProfil:String
    var nomPropriétaire:String
    var titreAnnonce:String
    var dateDébut:String
    var dateFin:String
    var lieu:[String]
    var département:String
    var photos: [String]
    var niveau:String
    var nombreDePlace:Int
    var descriptionAnimal:String
    var descriptionMaison:String
    var typologieAnimal: [String]

}



let tanyaK =  Annonce(photoDeProfil: "tanya-kusova-profil", nomPropriétaire: "Tanya Kusova", titreAnnonce: "2 chinchillas super friendly", dateDébut: "07.08.22", dateFin: "15.08.22", lieu: ["Paris", "ville"], département: "75020", photos: ["tanya-kusova-chinchilla2","tanya-kusova-chinchilla1","tanya-kusova-appartment"], niveau: "Connaisseur", nombreDePlace: 2, descriptionAnimal: "Si les chinchillas vivent en famille dans la nature, il n’en est pas de même en captivité. Pour un comportement social sans problème, la taille et l'aménagement de la cage seront déterminants. Généralement il est conseillé d'avoir deux chinchillas pour le bien-être des animaux. Deux mâles ou deux femelles peuvent cohabiter si les animaux se connaissent depuis leur prime jeunesse ou sont castrés. On peut également tenter d'introduire un congénère de même sexe et non castré plus tardivement si on respecte une période de quarantaine, mais il faudra être vigilant lors des premières rencontres. Une cage très spacieuse est dans tous les cas nécessaire si elle doit abriter plusieurs individus.", descriptionMaison: "Nous vous invitons à découvrir notre studio entièrement refait à neuf et décoré avec soin rue du Faubourg Saint-Denis, dans le coeur du 10ème arrondissement, à proximité des Grands Boulevards, de République et du Marais.Desservi par 8 lignes de métro & RER, il est idéalement situé pour découvrir tout Paris.",typologieAnimal: ["NAC", "Rongueur"])

let angelaB = Annonce(photoDeProfil: "angela-bailey-profil",nomPropriétaire: "Angela Bailey", titreAnnonce: "Chat miniature très calin", dateDébut: "28.06.22", dateFin: "30.06.22", lieu: ["Lyon","ville"], département: "69003", photos: ["angela-bailey-cat1","angela-bailey-cat2","angela-bailey-cat3","angela-bailey-house","angela-bailey-bedroom"], niveau: "Débutant", nombreDePlace: 2, descriptionAnimal: "Appréciant la compagnie, il est sociable et saura s'adapter à la présence d'autres animaux. Malgré sa petite taille, le Munchkin reste très dynamique et aime chasser, sauter et courir partout. D'où l'importance de lui offrir un arbre à chat dans le cas où il vit dans un appartement.", descriptionMaison: "Le logement est situé en plein centre ville, à 2 mns à pied du Vieux Lyon et 7 mns à pied de la place des Terreaux. Il est proche de la gare Saint-Paul, des transports en communs, des restaurants et pubs, face à la saône où il est possible de faire une balade en bâteau jusqu'au quartier Confluences. Il se trouve au 1er étage et est idéal pour un couple ou des amis qui souhaitent découvrir la ville de Lyon.", typologieAnimal: ["Chat"])

let nathanO = Annonce(photoDeProfil: "nathan-oakley-profil", nomPropriétaire: "Nathan Oakley", titreAnnonce: "Fredo le gueko et son appart'", dateDébut: "26.06.22", dateFin: "10.07.22", lieu: ["Brest","ville"], département: "29200", photos: ["nathan-oakley-gueko","nathan-oakley-home","nathan-oakley-bedroom"], niveau: "Débutant", nombreDePlace: 2, descriptionAnimal: "Le gecko léopard est un animal calme et plutôt timide. Il deviendra tout à fait manipulable, mais il faut y aller en douceur. A force de manipulation, il s'habituera à votre odeur, et finira par vous accepter, mais ne passez pas votre journée à le manipuler dès le premier jour, allez y progressivement.", descriptionMaison: "Appartement Cosy situé dans une rue calme , composé de deux pièces de 45 m², dans une résidence de standing sécurisée, situé dans le quartier Siam, au cœur du centre ville!Idéal pour un séjour professionnel ou des vacances, l'appartement est calme, lumineux et bien équipé ", typologieAnimal: ["Reptile", "NAC"])

let mattP = Annonce(photoDeProfil: "matt-pike-profil", nomPropriétaire: "Matt Pike", titreAnnonce: "Lapin en liberté dans appartement cosy", dateDébut: "19.10.22", dateFin: "30.10.22", lieu: ["Paris","ville"], département: "75001", photos: ["matt-pike-rabbit1","matt-pike-rabbit2","matt-pike-rabbit3","matt-pike-kitchen","matt-pike-home","matt-pike-desk"], niveau: "Débutant", nombreDePlace: 3, descriptionAnimal: "Le lapin ne fait généralement pas preuve d'agressivité envers ceux qui prennent soin de lui. Néanmoins, il peut parfois mordre, mais uniquement s'il se sent menacé ou s'il est stressé. Ce petit animal cohabite bien avec d'autres espèces animales.", descriptionMaison: "Magnifique appartement parisien, secteur Commerce, proche Tour Eiffel, Champ de Mars, bel immeuble calme et sécurisé (ascenseur, gardien). 44 m2. Au pied du métro ligne 8, proche lignes 6, 10 (10 min Concorde, Opéra). Idéal pour un séjour, expérience unique.Dans un bel immeuble en pierre de taille au 1er.", typologieAnimal: ["Rongeur", "NAC"])

let kaylaK = Annonce(photoDeProfil: "kayla-koss-profil", nomPropriétaire: "Kayla Koss", titreAnnonce: "Golden super friendly dans maison centre ville", dateDébut: "25.06.22", dateFin: "15.07.22", lieu: ["Bordeaux","ville"], département: "33000", photos: ["kayla-koss-dog4","kayla-dog3","kayla-koss-dog2","kayla-koss-dog1","kayla-koss-house","matt-pike-desk"], niveau: "Débutant", nombreDePlace: 3, descriptionAnimal: "Le Golden Retriever est l'une des races les plus populaires au monde tant il respire une attitude joviale et amicale. Son intelligence et son image de chien affectueux et parfait pour la famille expliquent ce succès. Son manteau or est caractéristique. C'est également un excellent nageur et apte pour le travail. La chasse, chien-guide d'aveugles, recherche et sauvetage sont des domaines où il excelle.", descriptionMaison: "Joli maison décoré avec soin, situé en hyper-centre (secteur Mériadeck) au 4e étage avec ascenseur. L'appartement se trouve dans une résidence hôtelière avec services. Place de parking comprise.", typologieAnimal: ["Chien"])

let jessicaB = Annonce(photoDeProfil: "jessica-burnett-profil", nomPropriétaire: "Jessica Burnett", titreAnnonce: "Un lama et des moutons dans vieille ferme rénovée", dateDébut: "23.07.22", dateFin: "30.07.22", lieu: ["Bodilis","campagne","ferme"], département: "29400", photos: ["jessica-burnett-goat1","jessica-burnett-goat2","jessica-burnett-house", "jessica-burnett-house2", "jessica-burnett-lama","jessica-burnett-garden"], niveau: "Amateur", nombreDePlace: 5, descriptionAnimal: "Les alpagas sont des animaux robustes originaires des hautes montagnes arides d'Amérique du Sud. On en trouve cependant de plus en plus dans nos contrées, et cela n'a rien de surprenant: ce sont des animaux curieux, faciles à vivre et à diriger. De plus, contrairement aux autres races de lamas, ils crachent rarement." , descriptionMaison: "Le gîte est une ancienne soue, de 21m2 au sol. La chambre est en mezzanine avec une hauteur sous poutre de 1m65. Les plus grands devront baisser la tête ! Rénovée avec goût, amour et des matériaux naturels locaux. Le gîte est situé dans un hameau très calme, au départ de nombreuses balades dans la forêt de Brocéliande. Notre jardin est mitoyen nous pourrons donc échanger et vous conseiller sur les restos, marchés, ballades, découvertes, si vous le souhaitez. Le terrain n'est pas cloturé.", typologieAnimal: ["Equidé", "Camélidés", "Atypique", "Ferme", "Montagne"])

let idellaM =  Annonce(photoDeProfil: "idella-maeland-profil", nomPropriétaire: "Idella Maeland", titreAnnonce: "Chevaux et chats dans une ferme à surveiller", dateDébut: "12.09.22", dateFin: "15.09.22", lieu: ["Nant","campagne","ferme"], département: "12230", photos: ["idella-maeland-babypony", "idella-maeland-goat2","idella-maeland-blackcow", "idella-maeland-babygoat", "idella-maeland-babycat", "idella-maeland-house1", "idella-maeland-house2", "idella-maeland-house3"], niveau: "Débutant", nombreDePlace: 2, descriptionAnimal: "Ils aiment aussi la tendresse et les câlins, c'est un point faible pour les chats. Ils ne se laissent toutefois pas approcher par tout le monde. À la base, un chat pourrait être effrayé par un cheval qui est un animal d'une plus grande taille. Il ne serait pas vraiment encouragé à l'approcher de très près", descriptionMaison: "Je vous accueille avec plaisir dans ce petit gite, mitoyen de la maison, au balcon des Gorges de la Dourbie face à un des plus beaux panoramas du Larzac. Du calme et du repos assuré, des espaces verts et la proximité d'activités variées.Bienvenue !", typologieAnimal: ["chevaux", "équidé", "cheval","ferme","chat"])

let johannaC =  Annonce(photoDeProfil: "Johanna cooper-profil", nomPropriétaire: "Johanna Cooper", titreAnnonce: "Des petits cochons à garder pendant ma convalescence", dateDébut: "10.12.22", dateFin: "05.01.23", lieu: ["Montpellier","campagne"], département: "34660", photos: ["johanna-cooper-babypig","Johanna-cooper-house1", "Johanna-cooper-house2", "Johanna-cooper-house3", "johanna-cooper-pig", "johanna-cooper-pig2", "johanna-cooper-pigandfriend"], niveau: "Débutant", nombreDePlace: 5, descriptionAnimal: "Mes animaux sont en liberté, mes cochons ont l'habitude des êtres humains. Ils sont très gentil et aime beaucoup allez se promener dans le jardin sous notre surveillance biensur.", descriptionMaison: "dans l'Hérault entre Sète et Montpellier, d'une petite maison sur terrain arboré construite en pierre et bois, contre la roche, dans l'angle d'une ancienne carrière.Sa magnifique baignoire intégrée dans la roche lui donne un charme exceptionnel.Il s'agit d'une belle chambre salle de bain avec une petite cuisine accolée. Sa belle petite terrasse et son jardin vous permettront de passer d'excellents moments à l'ombre ou au soleil.", typologieAnimal: ["ferme","cochon","atypique"])

let KarimM = Annonce(photoDeProfil: "karim-manjra-profil", nomPropriétaire: "Karim Manjra", titreAnnonce: "Des poules et des poussins dans une jolie maisonnette", dateDébut: "23.06.22", dateFin: "22.07.22", lieu: ["Carpentras","campagne"], département: "84380", photos: ["karim-manjra-babychicken","karim-manjra-bedroom", "karim-manjra-chichen", "karim-manjra-chickenout", "karim-manjra-house1"], niveau: "Débutant", nombreDePlace: 2, descriptionAnimal: "J'aime mes poules plus que tout, mais je pars souvent en déplacement pour des tournages ! Il faut les nourir tous les matins et regarder si les clotures ne sont pas habimer !.", descriptionMaison: "Bienvenu dans ma maison, il y a tout à disposition avec de très jolies balades à coté.", typologieAnimal: ["poule","poules","campagne","voilaille","oiseaux"])

let marcusC = Annonce(photoDeProfil: "marcus-cramer-profil", nomPropriétaire: "Marcus Cramer", titreAnnonce: "2 supers toutous à garder dans ferme rénovée", dateDébut: "05.08.22", dateFin: "15.08.22", lieu: ["Libourne","ferme","campagne"], département: "33500", photos: ["marcus-cramer-dog1","marcus-cramer-dog2", "marcus-cramer-house1", "marcus-cramer-house2"], niveau: "Connaisseur", nombreDePlace: 4, descriptionAnimal: "J'ai un berger allemand et un petit chien pékinoua, malheureusement l'un ne peut pas prendre l'avion et l'autre est trop âgé, je dois partir en déplacement quelques temps. Ils sont très très gentil.", descriptionMaison: "La chambre est équipée d'un lit 2 places en 140 avec matelas haut de gamme . Elle est aménagée d'un petit coin repas avec : table, Micro onde , mini-frigo ( 35 litres parfaitement silencieux) , cafetière et bouilloire . Télévision ( chaines TNT) . Wifi . Barbecue. Merci de prendre connaissance du règlement intérieur.", typologieAnimal: ["chien", "ferme"])

let mattW = Annonce(photoDeProfil: "matt-wildbore- profile", nomPropriétaire: "Matt Woldbore", titreAnnonce: "Des ânes et chevaux dans un jolie domaine", dateDébut: "17.07.22", dateFin: "25.07.22", lieu: ["Calvayrac","campagne"], département: "46220", photos: ["matt-wildbore-donkey","matt-wildbore-donkey2", "matt-wildbore-horse", "matt-wildbore-house","matt-wildbore-house2"], niveau: "Débutant", nombreDePlace: 4, descriptionAnimal: "La plupart des chevaux ont un ou plusieurs congénère(s) préféré(s). Ces préférences se manifestent par le temps passé côte à côte, sans nécessairement se toucher, pendant le repos ou le pâturage, le toilettage mutuel, la pratique du chasse-mouche tête bêche.", descriptionMaison: "Bienvenue à Calvayrac, colline verdoyante qui domine la vallée du Lot ! Célia et Matt vous accueillent dans un logement entier tout juste rénové, à la douce déco récup'. Entourés de verdure vous profiterez d'un grand espace extérieur privé et de bois à proximité. Le logement est très lumineux avec entrée indépendante d'une surface d'environ 70 mètres carrés . Il est au rez-de-jardin de notre maison, isolée sans voisin proche, où nous vivons avec nos deux jeunes enfants.", typologieAnimal: ["équidé","âne","chevaux","ferme"])

let patrickP = Annonce(photoDeProfil: "patrick-perkins-profil", nomPropriétaire: "Patrick Perkins", titreAnnonce: "Cochons d'Indes à garder pendant formation", dateDébut: "15.04.22", dateFin: "27.04.22", lieu: ["Nantes","ville"], département: "44000", photos: ["patrick-perkins-cochondinde3","patrick-perkins-cochondinde2","patrick-perkins-cochondinde1","patrick-perkins-house"], niveau: "Débutant", nombreDePlace: 3, descriptionAnimal: "A l’inverse d’autres petits rongeurs comme le hamster, le cochon d’Inde est un animal plutôt diurne, même s’il pourra aussi avoir des périodes d’activité la nuit. Ses jours seront découpés en plusieurs phases de repos et d’activité.Il aura besoin de sortir de sa cage durant de longs moments, même si ce n’est pas un grand sportif ! Plusieurs heures par jour, vous le laisserez en liberté (dans des lieux sécurisés) pour qu’il puisse se promener et satisfaire sa curiosité, en gardant toujours un œil sur lui bien sûr.", descriptionMaison: "Simplifiez-vous la vie dans ce logement calme et central à 10 minutes à pieds de la gare, 3 minutes de la cathédrale et 5 minutes du château.Entièrement rénové, il est constitué d'une pièce principale avec un espace cuisine- bureau- salon et un lit (90) ainsi que d'une salle d'eau. Il est situé au 3ème étage sans ascenseur.Pour votre confort, vous disposerez du linge de toilette et de maison.", typologieAnimal: ["nac","rongeur"])

// SUITE ANNONCE

let valerieE = Annonce(photoDeProfil: "valerie-elash-profil", nomPropriétaire: "Valerie Elash", titreAnnonce: "Wippet trop cool à garder en bord de place pendant nos vacances !", dateDébut: "20.06.22", dateFin: "01.07.22", lieu: ["Guetary","plage"], département: "64210", photos: ["valerie-elash-chien1","valerie-elash-chien2","valerie-elash-chien3","valerie-elash-appart3","valerie-elash-appart4","valerie-elash-appart1","valerie-elash-appart2"], niveau: "Débutant", nombreDePlace: 2, descriptionAnimal: "Le Whippet est un chien à la fois musclé et élancé. Son aspect général est d'une grande élégance et ses lignes sont pleines de grâce. Le Whippet (ou Lévrier nain), est taillé pour la vitesse. C'est un chien, au départ, fait pour la chasse. Sa grande rapidité a longtemps servi dans la chasse au lapin. D’ailleurs, il devra exprimer cette fougue quotidiennement. Il est parfaitement adapté à la vie de famille. Il n’aboie jamais et se montre très sociable, attendrissant, affectueux et sensible. Il ne demande aucun entretien particulier et possède une santé robuste. De plus, il peut très bien vivre en intérieur, surtout l’hiver.", descriptionMaison: "nd-lit (1 x 160 cm, longueur 200 cm), douche. Cuisine ouverte (four, lave-vaisselle, 3 plaques à induction, four micro-ondes, congélateur, cafetière électrique). Douche/WC, WC séparé. Chauffage électrique. Petit balcon. Très belle vue sur la localité, le port et l'océan. A disposition: lave-linge, fer à repasser, chaise haute pour enfant, lit bébé, sèche-cheveux. Internet (Connexion WIFI, gratuit). Place de parking près de la maison. Veuillez noter: logement non-fumeur. Détecteur de fumée. ", typologieAnimal: ["chien"])

let megS = Annonce(photoDeProfil: "meg-sanchez-profil", nomPropriétaire: "Meg Sanchez", titreAnnonce: "Gardiennage de nos ptits loups à Saint-tropez!", dateDébut: "05.08.22", dateFin: "15.08.22", lieu: ["Saint-tropez","plage"], département: "83990", photos: ["meg-sanchez-profil-chien2","meg-sanchez-profil-chien3","meg-sanchez-profil-chien1","meg-sanchez-profil-appart3","meg-sanchez-profil-appart1","meg-sanchez-profil-appart2"], niveau: "Débutant", nombreDePlace: 2, descriptionAnimal: "Toujours privilégier des temps individuels avec chacun de vos chiens. Leur proposer des occupations lors de vos absences car ce n'est pas parce qu'ils sont deux qu'ils s'occupent l'un l'autre. Répondre à leurs besoins sociaux (rencontres congénères) malgré le fait qu'ils soient toujours avec un autre chien.", descriptionMaison: "En plein coeur de la splendide cité lacustre de Port Grimaud, coquet appartement de type Studio Mezzanine offrant une vue panoramique sur les canaux.L’environnement exceptionnel qu’offre cet appartement saura vous ravir, d’autant plus qu’il se situe à seulement 400 m de la plage à pied.L’appartement a été complètement rénové pour vous offrir un logement tout confort.", typologieAnimal: ["chien"])

let wabeL = Annonce(photoDeProfil: "wabe-lambert-profil", nomPropriétaire: "Wabe Lambert", titreAnnonce: "Ptit toutou cool dans appart bord de place", dateDébut: "06.08.22", dateFin: "15.08.22", lieu: ["Gruissan","plage"], département: "11430", photos: ["wabe-lambert-chien1","wabe-lambert-chien2","wabe-lambert-appart1","wabe-lambert-appart2","wabe-lambert-appart3"], niveau: "Débutant", nombreDePlace: 2, descriptionAnimal: "Pour profiter des instants plage en toute sécurité avec votre chien, mieux vaut prendre quelques précautions et se poser quelques questions simples comme mon chien sait-il nager et est-il à l'aise dans l'eau ? Ai-je de quoi lui apporter un peu d'ombre et de fraîcheur pour éviter le coup de chaleur ? Ai-je de quoi le rincer après la baignade pour éviter les problèmes de peau dû aux baignades dans l'eau salée ? ... Faisons le tour ensemble de toutes ces questions pour des sorties mer réussies avec votre chien. ", descriptionMaison: "Il s’agit d’un appartement de 38m2 situé dans une résidence sécurisée avec une place de parking privé situé au 2ieme et dernier étage. Vous pourrez trouver à proximité la plage du grazel, balnéothérapie, parc d’attraction, accrobranche, mini golf ainsi que de nombreux commerces et restaurant.", typologieAnimal: ["chien"])

let kevinT = Annonce(photoDeProfil: "kevin-turcios-profil", nomPropriétaire: "Kevin Turcios", titreAnnonce: "Gardiennage de mon appart avec mon chien car formation", dateDébut: "06.08.22", dateFin: "15.08.22", lieu: ["Port La Nouvelle","plage"], département: "11210", photos: ["kevin-turcios-chien1","kevin-turcios-chien2","kevin-turcios-appart1","kevin-turcios-appart2"], niveau: "Débutant", nombreDePlace: 2, descriptionAnimal: "Vous adorez les chiens mais ne pouvez en avoir ? Je vous confis le mien gratuitement , le temps d’une promenade, de quelques heures, d’un weekend, et plus si affinités ! Promenez-vous, amusez-vous  et chouchoutez-le, pour son plus grand bonheur et pour le vôtre.", descriptionMaison: "Grand appartement rénové, tout équipé, avec balcon donnant sur la mer disposant d'une chambre avec lit double vue mer, et d'une chambre enfants avec 4 lits superposés, 2 grandes baies-vitrées avec vue imprenable sur la Méditerranée: du phare jusqu'au Pyrénées. ", typologieAnimal: ["chien"])

//


let yamonF = Annonce(photoDeProfil: "yamon-figurs-profil", nomPropriétaire: "Yamon Figurs", titreAnnonce: "Je fais garder mon Husky au pied du Mont Blanc", dateDébut: "20.12.22", dateFin: "15.01.23", lieu: ["Chamonix MB","montagne"], département: "74400", photos: ["yamon-figurs-chien1","yamon-figurs-chien2","yamon-figurs-appart3","yamon-figurs-appart2","yamon-figurs-appart1","yamon-figurs-chien3"], niveau: "Débutant", nombreDePlace: 2, descriptionAnimal: "Dans quelques jours ou quelques semaines, vous serez sur les pistes ? Vous partez en vacances à la neige avec votre chien ? Nous allons voir dans cet article comment préparer au mieux ces vacances froide, et profiter pleinement des joies de l'hiver en toute sécurité. Partir en vacances avec son chien à la neige : c'est Wouafement Bien mais ça se prépare ! Petit coup d'oeil sur tout ce qu'il faut savoir pour profiter de la neige avec son chien et profiter des plaisirs la montagne avec son chien.", descriptionMaison: "Apt 3 pièces 67 m2 au 1er étage. Aménagement avec beaucoup de bois: séjour/salle à manger avec TV et DVD. 1 chambre avec 1 grand-lit (140 cm, longueur 190 cm). 1 chambre avec 2 x 2 lits superposés (90 cm, longueur 190 cm).", typologieAnimal: ["chien"])

let daveR = Annonce(photoDeProfil: "dave ruck-profil", nomPropriétaire: "Dave Ruck", titreAnnonce: "Garder mes chèvres au milieu de la nature", dateDébut: "26.05.22", dateFin: "10.08.22", lieu: ["Saint Lary","montagne"], département: "65170", photos: ["dave ruck-house1","dave ruck-goat1","dave ruck-goat2","dave ruck-goat3","dave ruck-house3"], niveau: "Débutant", nombreDePlace: 2, descriptionAnimal: "Et si vous vous preniez pour un apprenti berger en vallée d’Aure ? Une balade avec les chèvres Angora d’Aulon, au coeur de la montagne, le temps d’une matinée conviviale, voilà l’activité familiale par excellence que vos enfants adoreront. Partez le temps d’une marche facile dans un cadre enchanteur, jusqu’au granges de Lurgues avec Céline qui vous parlera de son métier d’éleveur. A la rencontre des ses chèvres et chevreaux, vous découvrirez les soins aux animaux, la tonte, le travail du chien de berger et le mode de vie d’une exploitation en montagne dans ce magnifique village d’Aulon, tout près de St-Lary.", descriptionMaison: "Logement immergé dans la nature à 1921 slm, récemment rénové en hiver accessible uniquement avec des skis ou des raquettes.", typologieAnimal: ["chèvre","troupeau"])

let jeanfrançoisB = Annonce(photoDeProfil: "jf brou - profil", nomPropriétaire: "Jean François Brou", titreAnnonce: "Berger Blanc Suisse à garder à la montagne", dateDébut: "03.03.22", dateFin: "15.03.22", lieu: ["Chatel","montagne"], département: "74390", photos: ["jf brou - chien","jf brou - chien2","jf brou - appart","jf brou - appart2","jf brou - appart3"], niveau: "Débutant", nombreDePlace: 2, descriptionAnimal: "Tous les jours, beau temps mauvais temps, je sors après le petit déjeuner faire une marche avec mes chiens. Je fais généralement le même trajet de 3 km. L’exercice chez le chien est un besoin et c’est la clé d’un chien équilibré. Cesar Milan affirme que l’exercice «doit être la première, et la plus importante, des activités entre le chien et son maître».", descriptionMaison: "Détendez-vous dans cet appartement calme, élégant, rénové récemment dans un style campagnard moderne, à proximité du Lac de Vonnes et à côté de toutes commodités du centre de Châtel. Situé au 3ème étage d'une résidence de toute tranquillité, avec un grand balcon-bar, où vous aurez une vue exceptionnelle et panoramique sur Châtel et la Vallée d'Abondance, ainsi que sur les sommets du Châblais tel que: le Mont Chauffé, les Cornettes de Bises, Mont de Grange...", typologieAnimal: ["chien"])

let bernadetteS = Annonce(photoDeProfil: "bernadette souares - profil", nomPropriétaire: "Bernadette Sqaures", titreAnnonce: "Garder mon troupeau de vache à la montagne", dateDébut: "09.05.22", dateFin: "15.09.22", lieu: ["Saint Lary","montagne"], département: "65170", photos: ["bernadette souares - cow","bernadette souares - cow2","bernadette souares - house1","bernadette souares - house2","bernadette souares - house3"], niveau: "Débutant", nombreDePlace: 6, descriptionAnimal: "Par leur posture, les vaches signalent leurs intentions aux autres : agressivité (tête penchée et cornes vers l'avant), soumission (cou et tête baissé), curiosité (tête haute, cou étiré et museau en avant), etc. La communication sociale passe aussi par une sorte de « parfum émotionnel ».", descriptionMaison: "Le Chalet de Bernadette,chambre d'hôtes et spa privatif dans un environnement calme,pour un séjour atypique.Azet est idéalement situé, entre la Vallée d'Aure(Saint lary soulan à 6km) et la Vallée du Louron(Loudenvielle avec le lac et Balnéa ,centre balnéo ludique avec ses bains et ses soins à la carte). Entièrement réalisé par nos soins avec des matériaux de qualités,nous proposons une chambre haut de gamme avec de nombreux équipements qui vous permettrons de passer un agréable séjour", typologieAnimal: ["vache","troupeau"])


var annonces = [tanyaK, angelaB, nathanO, mattP, kaylaK, jessicaB, idellaM, johannaC, KarimM, marcusC, mattW, patrickP, valerieE, megS,wabeL, kevinT,yamonF, daveR, jeanfrançoisB, bernadetteS]
var annonceALaCampagne =  [jessicaB, idellaM, johannaC,KarimM,marcusC, mattW ]
var annoncesVille = [tanyaK, angelaB, nathanO, mattP,kaylaK, patrickP]
var annonceplage = [valerieE, megS,wabeL, kevinT]
var annoncemontagne = [yamonF, daveR, jeanfrançoisB, bernadetteS]
var coupdecoeurapp = [mattP, jessicaB, KarimM, valerieE, wabeL, daveR]
                


